// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: arquivos.proto

#ifndef PROTOBUF_arquivos_2eproto__INCLUDED
#define PROTOBUF_arquivos_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace ArquivosMsgProto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_arquivos_2eproto();
void protobuf_AssignDesc_arquivos_2eproto();
void protobuf_ShutdownFile_arquivos_2eproto();

class Arquivos;

// ===================================================================

class Arquivos : public ::google::protobuf::Message {
 public:
  Arquivos();
  virtual ~Arquivos();

  Arquivos(const Arquivos& from);

  inline Arquivos& operator=(const Arquivos& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Arquivos& default_instance();

  void Swap(Arquivos* other);

  // implements Message ----------------------------------------------

  Arquivos* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Arquivos& from);
  void MergeFrom(const Arquivos& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 nuvens = 1;
  inline bool has_nuvens() const;
  inline void clear_nuvens();
  static const int kNuvensFieldNumber = 1;
  inline ::google::protobuf::int32 nuvens() const;
  inline void set_nuvens(::google::protobuf::int32 value);

  // required int32 imagens = 2;
  inline bool has_imagens() const;
  inline void clear_imagens();
  static const int kImagensFieldNumber = 2;
  inline ::google::protobuf::int32 imagens() const;
  inline void set_imagens(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ArquivosMsgProto.Arquivos)
 private:
  inline void set_has_nuvens();
  inline void clear_has_nuvens();
  inline void set_has_imagens();
  inline void clear_has_imagens();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 nuvens_;
  ::google::protobuf::int32 imagens_;
  friend void  protobuf_AddDesc_arquivos_2eproto();
  friend void protobuf_AssignDesc_arquivos_2eproto();
  friend void protobuf_ShutdownFile_arquivos_2eproto();

  void InitAsDefaultInstance();
  static Arquivos* default_instance_;
};
// ===================================================================


// ===================================================================

// Arquivos

// required int32 nuvens = 1;
inline bool Arquivos::has_nuvens() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Arquivos::set_has_nuvens() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Arquivos::clear_has_nuvens() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Arquivos::clear_nuvens() {
  nuvens_ = 0;
  clear_has_nuvens();
}
inline ::google::protobuf::int32 Arquivos::nuvens() const {
  // @@protoc_insertion_point(field_get:ArquivosMsgProto.Arquivos.nuvens)
  return nuvens_;
}
inline void Arquivos::set_nuvens(::google::protobuf::int32 value) {
  set_has_nuvens();
  nuvens_ = value;
  // @@protoc_insertion_point(field_set:ArquivosMsgProto.Arquivos.nuvens)
}

// required int32 imagens = 2;
inline bool Arquivos::has_imagens() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Arquivos::set_has_imagens() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Arquivos::clear_has_imagens() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Arquivos::clear_imagens() {
  imagens_ = 0;
  clear_has_imagens();
}
inline ::google::protobuf::int32 Arquivos::imagens() const {
  // @@protoc_insertion_point(field_get:ArquivosMsgProto.Arquivos.imagens)
  return imagens_;
}
inline void Arquivos::set_imagens(::google::protobuf::int32 value) {
  set_has_imagens();
  imagens_ = value;
  // @@protoc_insertion_point(field_set:ArquivosMsgProto.Arquivos.imagens)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ArquivosMsgProto

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_arquivos_2eproto__INCLUDED
