// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: arquivos.proto

#ifndef PROTOBUF_arquivos_2eproto__INCLUDED
#define PROTOBUF_arquivos_2eproto__INCLUDED
#define PROTOBUF_USE_DLLS
#include <string>

#include <google/protobuf/stubs/common.h>
#define PROTOBUF_USE_DLLS
#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>

// @@protoc_insertion_point(includes)
namespace ArquivosMsgProto {
class Arquivos;
class ArquivosDefaultTypeInternal;
extern ArquivosDefaultTypeInternal _Arquivos_default_instance_;
}  // namespace ArquivosMsgProto

namespace ArquivosMsgProto {

namespace protobuf_arquivos_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_arquivos_2eproto

// ===================================================================

class Arquivos : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ArquivosMsgProto.Arquivos) */ {
 public:
  Arquivos();
  virtual ~Arquivos();

  Arquivos(const Arquivos& from);

  inline Arquivos& operator=(const Arquivos& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Arquivos& default_instance();

  static inline const Arquivos* internal_default_instance() {
    return reinterpret_cast<const Arquivos*>(
               &_Arquivos_default_instance_);
  }

  void Swap(Arquivos* other);

  // implements Message ----------------------------------------------

  inline Arquivos* New() const PROTOBUF_FINAL { return New(NULL); }

  Arquivos* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Arquivos& from);
  void MergeFrom(const Arquivos& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Arquivos* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 nuvens = 1;
  bool has_nuvens() const;
  void clear_nuvens();
  static const int kNuvensFieldNumber = 1;
  ::google::protobuf::int32 nuvens() const;
  void set_nuvens(::google::protobuf::int32 value);

  // required int32 imagens = 2;
  bool has_imagens() const;
  void clear_imagens();
  static const int kImagensFieldNumber = 2;
  ::google::protobuf::int32 imagens() const;
  void set_imagens(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ArquivosMsgProto.Arquivos)
 private:
  void set_has_nuvens();
  void clear_has_nuvens();
  void set_has_imagens();
  void clear_has_imagens();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 nuvens_;
  ::google::protobuf::int32 imagens_;
  friend struct  protobuf_arquivos_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Arquivos

// required int32 nuvens = 1;
inline bool Arquivos::has_nuvens() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Arquivos::set_has_nuvens() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Arquivos::clear_has_nuvens() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Arquivos::clear_nuvens() {
  nuvens_ = 0;
  clear_has_nuvens();
}
inline ::google::protobuf::int32 Arquivos::nuvens() const {
  // @@protoc_insertion_point(field_get:ArquivosMsgProto.Arquivos.nuvens)
  return nuvens_;
}
inline void Arquivos::set_nuvens(::google::protobuf::int32 value) {
  set_has_nuvens();
  nuvens_ = value;
  // @@protoc_insertion_point(field_set:ArquivosMsgProto.Arquivos.nuvens)
}

// required int32 imagens = 2;
inline bool Arquivos::has_imagens() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Arquivos::set_has_imagens() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Arquivos::clear_has_imagens() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Arquivos::clear_imagens() {
  imagens_ = 0;
  clear_has_imagens();
}
inline ::google::protobuf::int32 Arquivos::imagens() const {
  // @@protoc_insertion_point(field_get:ArquivosMsgProto.Arquivos.imagens)
  return imagens_;
}
inline void Arquivos::set_imagens(::google::protobuf::int32 value) {
  set_has_imagens();
  imagens_ = value;
  // @@protoc_insertion_point(field_set:ArquivosMsgProto.Arquivos.imagens)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace ArquivosMsgProto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_arquivos_2eproto__INCLUDED
