// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: arquivos.proto

#ifndef PROTOBUF_arquivos_2eproto__INCLUDED
#define PROTOBUF_arquivos_2eproto__INCLUDED

#include <string>
#define PROTOBUF_USE_DLLS
#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace ArquivosMsgProto {
class Arquivos;
class ArquivosDefaultTypeInternal;
extern ArquivosDefaultTypeInternal _Arquivos_default_instance_;
}  // namespace ArquivosMsgProto

namespace ArquivosMsgProto {

namespace protobuf_arquivos_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_arquivos_2eproto

// ===================================================================

class Arquivos : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ArquivosMsgProto.Arquivos) */ {
 public:
  Arquivos();
  virtual ~Arquivos();

  Arquivos(const Arquivos& from);

  inline Arquivos& operator=(const Arquivos& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Arquivos& default_instance();

  static inline const Arquivos* internal_default_instance() {
    return reinterpret_cast<const Arquivos*>(
               &_Arquivos_default_instance_);
  }

  void Swap(Arquivos* other);

  // implements Message ----------------------------------------------

  inline Arquivos* New() const PROTOBUF_FINAL { return New(NULL); }

  Arquivos* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Arquivos& from);
  void MergeFrom(const Arquivos& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Arquivos* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string pasta = 1;
  void clear_pasta();
  static const int kPastaFieldNumber = 1;
  const ::std::string& pasta() const;
  void set_pasta(const ::std::string& value);
  #if LANG_CXX11
  void set_pasta(::std::string&& value);
  #endif
  void set_pasta(const char* value);
  void set_pasta(const char* value, size_t size);
  ::std::string* mutable_pasta();
  ::std::string* release_pasta();
  void set_allocated_pasta(::std::string* pasta);

  // int32 nuvens = 2;
  void clear_nuvens();
  static const int kNuvensFieldNumber = 2;
  ::google::protobuf::int32 nuvens() const;
  void set_nuvens(::google::protobuf::int32 value);

  // int32 imagens = 3;
  void clear_imagens();
  static const int kImagensFieldNumber = 3;
  ::google::protobuf::int32 imagens() const;
  void set_imagens(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ArquivosMsgProto.Arquivos)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr pasta_;
  ::google::protobuf::int32 nuvens_;
  ::google::protobuf::int32 imagens_;
  mutable int _cached_size_;
  friend struct  protobuf_arquivos_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Arquivos

// string pasta = 1;
inline void Arquivos::clear_pasta() {
  pasta_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Arquivos::pasta() const {
  // @@protoc_insertion_point(field_get:ArquivosMsgProto.Arquivos.pasta)
  return pasta_.GetNoArena();
}
inline void Arquivos::set_pasta(const ::std::string& value) {
  
  pasta_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ArquivosMsgProto.Arquivos.pasta)
}
#if LANG_CXX11
inline void Arquivos::set_pasta(::std::string&& value) {
  
  pasta_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ArquivosMsgProto.Arquivos.pasta)
}
#endif
inline void Arquivos::set_pasta(const char* value) {
  
  pasta_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ArquivosMsgProto.Arquivos.pasta)
}
inline void Arquivos::set_pasta(const char* value, size_t size) {
  
  pasta_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ArquivosMsgProto.Arquivos.pasta)
}
inline ::std::string* Arquivos::mutable_pasta() {
  
  // @@protoc_insertion_point(field_mutable:ArquivosMsgProto.Arquivos.pasta)
  return pasta_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Arquivos::release_pasta() {
  // @@protoc_insertion_point(field_release:ArquivosMsgProto.Arquivos.pasta)
  
  return pasta_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Arquivos::set_allocated_pasta(::std::string* pasta) {
  if (pasta != NULL) {
    
  } else {
    
  }
  pasta_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), pasta);
  // @@protoc_insertion_point(field_set_allocated:ArquivosMsgProto.Arquivos.pasta)
}

// int32 nuvens = 2;
inline void Arquivos::clear_nuvens() {
  nuvens_ = 0;
}
inline ::google::protobuf::int32 Arquivos::nuvens() const {
  // @@protoc_insertion_point(field_get:ArquivosMsgProto.Arquivos.nuvens)
  return nuvens_;
}
inline void Arquivos::set_nuvens(::google::protobuf::int32 value) {
  
  nuvens_ = value;
  // @@protoc_insertion_point(field_set:ArquivosMsgProto.Arquivos.nuvens)
}

// int32 imagens = 3;
inline void Arquivos::clear_imagens() {
  imagens_ = 0;
}
inline ::google::protobuf::int32 Arquivos::imagens() const {
  // @@protoc_insertion_point(field_get:ArquivosMsgProto.Arquivos.imagens)
  return imagens_;
}
inline void Arquivos::set_imagens(::google::protobuf::int32 value) {
  
  imagens_ = value;
  // @@protoc_insertion_point(field_set:ArquivosMsgProto.Arquivos.imagens)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace ArquivosMsgProto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_arquivos_2eproto__INCLUDED
