// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: arquivos.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "arquivos.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ArquivosMsgProto {
class ArquivosDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Arquivos> {
} _Arquivos_default_instance_;

namespace protobuf_arquivos_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Arquivos, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Arquivos, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Arquivos, nuvens_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Arquivos, imagens_),
  0,
  1,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 6, sizeof(Arquivos)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_Arquivos_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "arquivos.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _Arquivos_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _Arquivos_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\016arquivos.proto\022\020ArquivosMsgProto\"+\n\010Ar"
      "quivos\022\016\n\006nuvens\030\001 \002(\005\022\017\n\007imagens\030\002 \002(\005"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 79);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "arquivos.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_arquivos_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Arquivos::kNuvensFieldNumber;
const int Arquivos::kImagensFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Arquivos::Arquivos()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_arquivos_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:ArquivosMsgProto.Arquivos)
}
Arquivos::Arquivos(const Arquivos& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&nuvens_, &from.nuvens_,
    reinterpret_cast<char*>(&imagens_) -
    reinterpret_cast<char*>(&nuvens_) + sizeof(imagens_));
  // @@protoc_insertion_point(copy_constructor:ArquivosMsgProto.Arquivos)
}

void Arquivos::SharedCtor() {
  _cached_size_ = 0;
  ::memset(&nuvens_, 0, reinterpret_cast<char*>(&imagens_) -
    reinterpret_cast<char*>(&nuvens_) + sizeof(imagens_));
}

Arquivos::~Arquivos() {
  // @@protoc_insertion_point(destructor:ArquivosMsgProto.Arquivos)
  SharedDtor();
}

void Arquivos::SharedDtor() {
}

void Arquivos::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Arquivos::descriptor() {
  protobuf_arquivos_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_arquivos_2eproto::file_level_metadata[0].descriptor;
}

const Arquivos& Arquivos::default_instance() {
  protobuf_arquivos_2eproto::InitDefaults();
  return *internal_default_instance();
}

Arquivos* Arquivos::New(::google::protobuf::Arena* arena) const {
  Arquivos* n = new Arquivos;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Arquivos::Clear() {
// @@protoc_insertion_point(message_clear_start:ArquivosMsgProto.Arquivos)
  if (_has_bits_[0 / 32] & 3u) {
    ::memset(&nuvens_, 0, reinterpret_cast<char*>(&imagens_) -
      reinterpret_cast<char*>(&nuvens_) + sizeof(imagens_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Arquivos::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ArquivosMsgProto.Arquivos)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 nuvens = 1;
      case 1: {
        if (tag == 8u) {
          set_has_nuvens();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &nuvens_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 imagens = 2;
      case 2: {
        if (tag == 16u) {
          set_has_imagens();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &imagens_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ArquivosMsgProto.Arquivos)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ArquivosMsgProto.Arquivos)
  return false;
#undef DO_
}

void Arquivos::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ArquivosMsgProto.Arquivos)
  // required int32 nuvens = 1;
  if (has_nuvens()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->nuvens(), output);
  }

  // required int32 imagens = 2;
  if (has_imagens()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->imagens(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ArquivosMsgProto.Arquivos)
}

::google::protobuf::uint8* Arquivos::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ArquivosMsgProto.Arquivos)
  // required int32 nuvens = 1;
  if (has_nuvens()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->nuvens(), target);
  }

  // required int32 imagens = 2;
  if (has_imagens()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->imagens(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ArquivosMsgProto.Arquivos)
  return target;
}

size_t Arquivos::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:ArquivosMsgProto.Arquivos)
  size_t total_size = 0;

  if (has_nuvens()) {
    // required int32 nuvens = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->nuvens());
  }

  if (has_imagens()) {
    // required int32 imagens = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->imagens());
  }

  return total_size;
}
size_t Arquivos::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ArquivosMsgProto.Arquivos)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required int32 nuvens = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->nuvens());

    // required int32 imagens = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->imagens());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Arquivos::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ArquivosMsgProto.Arquivos)
  GOOGLE_DCHECK_NE(&from, this);
  const Arquivos* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Arquivos>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ArquivosMsgProto.Arquivos)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ArquivosMsgProto.Arquivos)
    MergeFrom(*source);
  }
}

void Arquivos::MergeFrom(const Arquivos& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ArquivosMsgProto.Arquivos)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from._has_bits_[0 / 32] & 3u) {
    if (from.has_nuvens()) {
      set_nuvens(from.nuvens());
    }
    if (from.has_imagens()) {
      set_imagens(from.imagens());
    }
  }
}

void Arquivos::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ArquivosMsgProto.Arquivos)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Arquivos::CopyFrom(const Arquivos& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ArquivosMsgProto.Arquivos)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Arquivos::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  return true;
}

void Arquivos::Swap(Arquivos* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Arquivos::InternalSwap(Arquivos* other) {
  std::swap(nuvens_, other->nuvens_);
  std::swap(imagens_, other->imagens_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Arquivos::GetMetadata() const {
  protobuf_arquivos_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_arquivos_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Arquivos

// required int32 nuvens = 1;
bool Arquivos::has_nuvens() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void Arquivos::set_has_nuvens() {
  _has_bits_[0] |= 0x00000001u;
}
void Arquivos::clear_has_nuvens() {
  _has_bits_[0] &= ~0x00000001u;
}
void Arquivos::clear_nuvens() {
  nuvens_ = 0;
  clear_has_nuvens();
}
::google::protobuf::int32 Arquivos::nuvens() const {
  // @@protoc_insertion_point(field_get:ArquivosMsgProto.Arquivos.nuvens)
  return nuvens_;
}
void Arquivos::set_nuvens(::google::protobuf::int32 value) {
  set_has_nuvens();
  nuvens_ = value;
  // @@protoc_insertion_point(field_set:ArquivosMsgProto.Arquivos.nuvens)
}

// required int32 imagens = 2;
bool Arquivos::has_imagens() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void Arquivos::set_has_imagens() {
  _has_bits_[0] |= 0x00000002u;
}
void Arquivos::clear_has_imagens() {
  _has_bits_[0] &= ~0x00000002u;
}
void Arquivos::clear_imagens() {
  imagens_ = 0;
  clear_has_imagens();
}
::google::protobuf::int32 Arquivos::imagens() const {
  // @@protoc_insertion_point(field_get:ArquivosMsgProto.Arquivos.imagens)
  return imagens_;
}
void Arquivos::set_imagens(::google::protobuf::int32 value) {
  set_has_imagens();
  imagens_ = value;
  // @@protoc_insertion_point(field_set:ArquivosMsgProto.Arquivos.imagens)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace ArquivosMsgProto

// @@protoc_insertion_point(global_scope)
