// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: arquivos.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "arquivos.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ArquivosMsgProto {

namespace {

const ::google::protobuf::Descriptor* Arquivos_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Arquivos_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_arquivos_2eproto() {
  protobuf_AddDesc_arquivos_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "arquivos.proto");
  GOOGLE_CHECK(file != NULL);
  Arquivos_descriptor_ = file->message_type(0);
  static const int Arquivos_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Arquivos, nuvens_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Arquivos, imagens_),
  };
  Arquivos_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Arquivos_descriptor_,
      Arquivos::default_instance_,
      Arquivos_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Arquivos, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Arquivos, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Arquivos));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_arquivos_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Arquivos_descriptor_, &Arquivos::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_arquivos_2eproto() {
  delete Arquivos::default_instance_;
  delete Arquivos_reflection_;
}

void protobuf_AddDesc_arquivos_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\016arquivos.proto\022\020ArquivosMsgProto\"+\n\010Ar"
    "quivos\022\016\n\006nuvens\030\001 \002(\005\022\017\n\007imagens\030\002 \002(\005", 79);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "arquivos.proto", &protobuf_RegisterTypes);
  Arquivos::default_instance_ = new Arquivos();
  Arquivos::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_arquivos_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_arquivos_2eproto {
  StaticDescriptorInitializer_arquivos_2eproto() {
    protobuf_AddDesc_arquivos_2eproto();
  }
} static_descriptor_initializer_arquivos_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Arquivos::kNuvensFieldNumber;
const int Arquivos::kImagensFieldNumber;
#endif  // !_MSC_VER

Arquivos::Arquivos()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ArquivosMsgProto.Arquivos)
}

void Arquivos::InitAsDefaultInstance() {
}

Arquivos::Arquivos(const Arquivos& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:ArquivosMsgProto.Arquivos)
}

void Arquivos::SharedCtor() {
  _cached_size_ = 0;
  nuvens_ = 0;
  imagens_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Arquivos::~Arquivos() {
  // @@protoc_insertion_point(destructor:ArquivosMsgProto.Arquivos)
  SharedDtor();
}

void Arquivos::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Arquivos::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Arquivos::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Arquivos_descriptor_;
}

const Arquivos& Arquivos::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_arquivos_2eproto();
  return *default_instance_;
}

Arquivos* Arquivos::default_instance_ = NULL;

Arquivos* Arquivos::New() const {
  return new Arquivos;
}

void Arquivos::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<Arquivos*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(nuvens_, imagens_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Arquivos::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ArquivosMsgProto.Arquivos)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 nuvens = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &nuvens_)));
          set_has_nuvens();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_imagens;
        break;
      }

      // required int32 imagens = 2;
      case 2: {
        if (tag == 16) {
         parse_imagens:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &imagens_)));
          set_has_imagens();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ArquivosMsgProto.Arquivos)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ArquivosMsgProto.Arquivos)
  return false;
#undef DO_
}

void Arquivos::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ArquivosMsgProto.Arquivos)
  // required int32 nuvens = 1;
  if (has_nuvens()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->nuvens(), output);
  }

  // required int32 imagens = 2;
  if (has_imagens()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->imagens(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ArquivosMsgProto.Arquivos)
}

::google::protobuf::uint8* Arquivos::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ArquivosMsgProto.Arquivos)
  // required int32 nuvens = 1;
  if (has_nuvens()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->nuvens(), target);
  }

  // required int32 imagens = 2;
  if (has_imagens()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->imagens(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ArquivosMsgProto.Arquivos)
  return target;
}

int Arquivos::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 nuvens = 1;
    if (has_nuvens()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->nuvens());
    }

    // required int32 imagens = 2;
    if (has_imagens()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->imagens());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Arquivos::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Arquivos* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Arquivos*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Arquivos::MergeFrom(const Arquivos& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_nuvens()) {
      set_nuvens(from.nuvens());
    }
    if (from.has_imagens()) {
      set_imagens(from.imagens());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Arquivos::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Arquivos::CopyFrom(const Arquivos& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Arquivos::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void Arquivos::Swap(Arquivos* other) {
  if (other != this) {
    std::swap(nuvens_, other->nuvens_);
    std::swap(imagens_, other->imagens_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Arquivos::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Arquivos_descriptor_;
  metadata.reflection = Arquivos_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ArquivosMsgProto

// @@protoc_insertion_point(global_scope)
