// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: arquivos.proto

#include "arquivos.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace ArquivosMsgProto {
class ArquivosDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Arquivos> _instance;
} _Arquivos_default_instance_;
}  // namespace ArquivosMsgProto
static void InitDefaultsscc_info_Arquivos_arquivos_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ArquivosMsgProto::_Arquivos_default_instance_;
    new (ptr) ::ArquivosMsgProto::Arquivos();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ArquivosMsgProto::Arquivos::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Arquivos_arquivos_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Arquivos_arquivos_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_arquivos_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_arquivos_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_arquivos_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_arquivos_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ArquivosMsgProto::Arquivos, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::ArquivosMsgProto::Arquivos, pasta_),
  PROTOBUF_FIELD_OFFSET(::ArquivosMsgProto::Arquivos, nuvens_),
  PROTOBUF_FIELD_OFFSET(::ArquivosMsgProto::Arquivos, imagens_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::ArquivosMsgProto::Arquivos)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::ArquivosMsgProto::_Arquivos_default_instance_),
};

const char descriptor_table_protodef_arquivos_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016arquivos.proto\022\020ArquivosMsgProto\":\n\010Ar"
  "quivos\022\r\n\005pasta\030\001 \001(\t\022\016\n\006nuvens\030\002 \001(\005\022\017\n"
  "\007imagens\030\003 \001(\005b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_arquivos_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_arquivos_2eproto_sccs[1] = {
  &scc_info_Arquivos_arquivos_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_arquivos_2eproto_once;
static bool descriptor_table_arquivos_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_arquivos_2eproto = {
  &descriptor_table_arquivos_2eproto_initialized, descriptor_table_protodef_arquivos_2eproto, "arquivos.proto", 102,
  &descriptor_table_arquivos_2eproto_once, descriptor_table_arquivos_2eproto_sccs, descriptor_table_arquivos_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_arquivos_2eproto::offsets,
  file_level_metadata_arquivos_2eproto, 1, file_level_enum_descriptors_arquivos_2eproto, file_level_service_descriptors_arquivos_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_arquivos_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_arquivos_2eproto), true);
namespace ArquivosMsgProto {

// ===================================================================

void Arquivos::InitAsDefaultInstance() {
}
class Arquivos::_Internal {
 public:
};

Arquivos::Arquivos()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ArquivosMsgProto.Arquivos)
}
Arquivos::Arquivos(const Arquivos& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  pasta_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_pasta().empty()) {
    pasta_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.pasta_);
  }
  ::memcpy(&nuvens_, &from.nuvens_,
    static_cast<size_t>(reinterpret_cast<char*>(&imagens_) -
    reinterpret_cast<char*>(&nuvens_)) + sizeof(imagens_));
  // @@protoc_insertion_point(copy_constructor:ArquivosMsgProto.Arquivos)
}

void Arquivos::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_Arquivos_arquivos_2eproto.base);
  pasta_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&nuvens_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&imagens_) -
      reinterpret_cast<char*>(&nuvens_)) + sizeof(imagens_));
}

Arquivos::~Arquivos() {
  // @@protoc_insertion_point(destructor:ArquivosMsgProto.Arquivos)
  SharedDtor();
}

void Arquivos::SharedDtor() {
  pasta_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void Arquivos::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Arquivos& Arquivos::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Arquivos_arquivos_2eproto.base);
  return *internal_default_instance();
}


void Arquivos::Clear() {
// @@protoc_insertion_point(message_clear_start:ArquivosMsgProto.Arquivos)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  pasta_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&nuvens_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&imagens_) -
      reinterpret_cast<char*>(&nuvens_)) + sizeof(imagens_));
  _internal_metadata_.Clear();
}

const char* Arquivos::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string pasta = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_pasta();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "ArquivosMsgProto.Arquivos.pasta"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 nuvens = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          nuvens_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 imagens = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          imagens_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Arquivos::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ArquivosMsgProto.Arquivos)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string pasta = 1;
  if (this->pasta().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_pasta().data(), static_cast<int>(this->_internal_pasta().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ArquivosMsgProto.Arquivos.pasta");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_pasta(), target);
  }

  // int32 nuvens = 2;
  if (this->nuvens() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_nuvens(), target);
  }

  // int32 imagens = 3;
  if (this->imagens() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_imagens(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ArquivosMsgProto.Arquivos)
  return target;
}

size_t Arquivos::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ArquivosMsgProto.Arquivos)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string pasta = 1;
  if (this->pasta().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_pasta());
  }

  // int32 nuvens = 2;
  if (this->nuvens() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_nuvens());
  }

  // int32 imagens = 3;
  if (this->imagens() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_imagens());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Arquivos::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ArquivosMsgProto.Arquivos)
  GOOGLE_DCHECK_NE(&from, this);
  const Arquivos* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Arquivos>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ArquivosMsgProto.Arquivos)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ArquivosMsgProto.Arquivos)
    MergeFrom(*source);
  }
}

void Arquivos::MergeFrom(const Arquivos& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ArquivosMsgProto.Arquivos)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.pasta().size() > 0) {

    pasta_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.pasta_);
  }
  if (from.nuvens() != 0) {
    _internal_set_nuvens(from._internal_nuvens());
  }
  if (from.imagens() != 0) {
    _internal_set_imagens(from._internal_imagens());
  }
}

void Arquivos::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ArquivosMsgProto.Arquivos)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Arquivos::CopyFrom(const Arquivos& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ArquivosMsgProto.Arquivos)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Arquivos::IsInitialized() const {
  return true;
}

void Arquivos::InternalSwap(Arquivos* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  pasta_.Swap(&other->pasta_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(nuvens_, other->nuvens_);
  swap(imagens_, other->imagens_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Arquivos::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace ArquivosMsgProto
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ArquivosMsgProto::Arquivos* Arena::CreateMaybeMessage< ::ArquivosMsgProto::Arquivos >(Arena* arena) {
  return Arena::CreateInternal< ::ArquivosMsgProto::Arquivos >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
