// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nuvem.proto

#ifndef PROTOBUF_nuvem_2eproto__INCLUDED
#define PROTOBUF_nuvem_2eproto__INCLUDED
#define PROTOBUF_USE_DLLS
#include <string>

#include <google/protobuf/stubs/common.h>
#define PROTOBUF_USE_DLLS
#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace NuvemMsgProto {
class Nuvem;
class NuvemDefaultTypeInternal;
extern NuvemDefaultTypeInternal _Nuvem_default_instance_;
class Nuvem_Ponto;
class Nuvem_PontoDefaultTypeInternal;
extern Nuvem_PontoDefaultTypeInternal _Nuvem_Ponto_default_instance_;
}  // namespace NuvemMsgProto

namespace NuvemMsgProto {

namespace protobuf_nuvem_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_nuvem_2eproto

// ===================================================================

class Nuvem_Ponto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:NuvemMsgProto.Nuvem.Ponto) */ {
 public:
  Nuvem_Ponto();
  virtual ~Nuvem_Ponto();

  Nuvem_Ponto(const Nuvem_Ponto& from);

  inline Nuvem_Ponto& operator=(const Nuvem_Ponto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Nuvem_Ponto& default_instance();

  static inline const Nuvem_Ponto* internal_default_instance() {
    return reinterpret_cast<const Nuvem_Ponto*>(
               &_Nuvem_Ponto_default_instance_);
  }

  void Swap(Nuvem_Ponto* other);

  // implements Message ----------------------------------------------

  inline Nuvem_Ponto* New() const PROTOBUF_FINAL { return New(NULL); }

  Nuvem_Ponto* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Nuvem_Ponto& from);
  void MergeFrom(const Nuvem_Ponto& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Nuvem_Ponto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double x = 1;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 1;
  double x() const;
  void set_x(double value);

  // required double y = 2;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 2;
  double y() const;
  void set_y(double value);

  // required double z = 3;
  bool has_z() const;
  void clear_z();
  static const int kZFieldNumber = 3;
  double z() const;
  void set_z(double value);

  // required int32 r = 4;
  bool has_r() const;
  void clear_r();
  static const int kRFieldNumber = 4;
  ::google::protobuf::int32 r() const;
  void set_r(::google::protobuf::int32 value);

  // required int32 g = 5;
  bool has_g() const;
  void clear_g();
  static const int kGFieldNumber = 5;
  ::google::protobuf::int32 g() const;
  void set_g(::google::protobuf::int32 value);

  // required int32 b = 6;
  bool has_b() const;
  void clear_b();
  static const int kBFieldNumber = 6;
  ::google::protobuf::int32 b() const;
  void set_b(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:NuvemMsgProto.Nuvem.Ponto)
 private:
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();
  void set_has_z();
  void clear_has_z();
  void set_has_r();
  void clear_has_r();
  void set_has_g();
  void clear_has_g();
  void set_has_b();
  void clear_has_b();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  double x_;
  double y_;
  double z_;
  ::google::protobuf::int32 r_;
  ::google::protobuf::int32 g_;
  ::google::protobuf::int32 b_;
  friend struct  protobuf_nuvem_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Nuvem : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:NuvemMsgProto.Nuvem) */ {
 public:
  Nuvem();
  virtual ~Nuvem();

  Nuvem(const Nuvem& from);

  inline Nuvem& operator=(const Nuvem& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Nuvem& default_instance();

  static inline const Nuvem* internal_default_instance() {
    return reinterpret_cast<const Nuvem*>(
               &_Nuvem_default_instance_);
  }

  void Swap(Nuvem* other);

  // implements Message ----------------------------------------------

  inline Nuvem* New() const PROTOBUF_FINAL { return New(NULL); }

  Nuvem* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Nuvem& from);
  void MergeFrom(const Nuvem& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Nuvem* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef Nuvem_Ponto Ponto;

  // accessors -------------------------------------------------------

  // repeated .NuvemMsgProto.Nuvem.Ponto pontos = 3;
  int pontos_size() const;
  void clear_pontos();
  static const int kPontosFieldNumber = 3;
  const ::NuvemMsgProto::Nuvem_Ponto& pontos(int index) const;
  ::NuvemMsgProto::Nuvem_Ponto* mutable_pontos(int index);
  ::NuvemMsgProto::Nuvem_Ponto* add_pontos();
  ::google::protobuf::RepeatedPtrField< ::NuvemMsgProto::Nuvem_Ponto >*
      mutable_pontos();
  const ::google::protobuf::RepeatedPtrField< ::NuvemMsgProto::Nuvem_Ponto >&
      pontos() const;

  // required string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // required int32 size = 2;
  bool has_size() const;
  void clear_size();
  static const int kSizeFieldNumber = 2;
  ::google::protobuf::int32 size() const;
  void set_size(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:NuvemMsgProto.Nuvem)
 private:
  void set_has_name();
  void clear_has_name();
  void set_has_size();
  void clear_has_size();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::NuvemMsgProto::Nuvem_Ponto > pontos_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::int32 size_;
  friend struct  protobuf_nuvem_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Nuvem_Ponto

// required double x = 1;
inline bool Nuvem_Ponto::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Nuvem_Ponto::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Nuvem_Ponto::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Nuvem_Ponto::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline double Nuvem_Ponto::x() const {
  // @@protoc_insertion_point(field_get:NuvemMsgProto.Nuvem.Ponto.x)
  return x_;
}
inline void Nuvem_Ponto::set_x(double value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:NuvemMsgProto.Nuvem.Ponto.x)
}

// required double y = 2;
inline bool Nuvem_Ponto::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Nuvem_Ponto::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Nuvem_Ponto::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Nuvem_Ponto::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline double Nuvem_Ponto::y() const {
  // @@protoc_insertion_point(field_get:NuvemMsgProto.Nuvem.Ponto.y)
  return y_;
}
inline void Nuvem_Ponto::set_y(double value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:NuvemMsgProto.Nuvem.Ponto.y)
}

// required double z = 3;
inline bool Nuvem_Ponto::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Nuvem_Ponto::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Nuvem_Ponto::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Nuvem_Ponto::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline double Nuvem_Ponto::z() const {
  // @@protoc_insertion_point(field_get:NuvemMsgProto.Nuvem.Ponto.z)
  return z_;
}
inline void Nuvem_Ponto::set_z(double value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:NuvemMsgProto.Nuvem.Ponto.z)
}

// required int32 r = 4;
inline bool Nuvem_Ponto::has_r() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Nuvem_Ponto::set_has_r() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Nuvem_Ponto::clear_has_r() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Nuvem_Ponto::clear_r() {
  r_ = 0;
  clear_has_r();
}
inline ::google::protobuf::int32 Nuvem_Ponto::r() const {
  // @@protoc_insertion_point(field_get:NuvemMsgProto.Nuvem.Ponto.r)
  return r_;
}
inline void Nuvem_Ponto::set_r(::google::protobuf::int32 value) {
  set_has_r();
  r_ = value;
  // @@protoc_insertion_point(field_set:NuvemMsgProto.Nuvem.Ponto.r)
}

// required int32 g = 5;
inline bool Nuvem_Ponto::has_g() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Nuvem_Ponto::set_has_g() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Nuvem_Ponto::clear_has_g() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Nuvem_Ponto::clear_g() {
  g_ = 0;
  clear_has_g();
}
inline ::google::protobuf::int32 Nuvem_Ponto::g() const {
  // @@protoc_insertion_point(field_get:NuvemMsgProto.Nuvem.Ponto.g)
  return g_;
}
inline void Nuvem_Ponto::set_g(::google::protobuf::int32 value) {
  set_has_g();
  g_ = value;
  // @@protoc_insertion_point(field_set:NuvemMsgProto.Nuvem.Ponto.g)
}

// required int32 b = 6;
inline bool Nuvem_Ponto::has_b() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Nuvem_Ponto::set_has_b() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Nuvem_Ponto::clear_has_b() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Nuvem_Ponto::clear_b() {
  b_ = 0;
  clear_has_b();
}
inline ::google::protobuf::int32 Nuvem_Ponto::b() const {
  // @@protoc_insertion_point(field_get:NuvemMsgProto.Nuvem.Ponto.b)
  return b_;
}
inline void Nuvem_Ponto::set_b(::google::protobuf::int32 value) {
  set_has_b();
  b_ = value;
  // @@protoc_insertion_point(field_set:NuvemMsgProto.Nuvem.Ponto.b)
}

// -------------------------------------------------------------------

// Nuvem

// required string name = 1;
inline bool Nuvem::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Nuvem::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Nuvem::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Nuvem::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& Nuvem::name() const {
  // @@protoc_insertion_point(field_get:NuvemMsgProto.Nuvem.name)
  return name_.GetNoArena();
}
inline void Nuvem::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:NuvemMsgProto.Nuvem.name)
}
#if LANG_CXX11
inline void Nuvem::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:NuvemMsgProto.Nuvem.name)
}
#endif
inline void Nuvem::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:NuvemMsgProto.Nuvem.name)
}
inline void Nuvem::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:NuvemMsgProto.Nuvem.name)
}
inline ::std::string* Nuvem::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:NuvemMsgProto.Nuvem.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Nuvem::release_name() {
  // @@protoc_insertion_point(field_release:NuvemMsgProto.Nuvem.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Nuvem::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:NuvemMsgProto.Nuvem.name)
}

// required int32 size = 2;
inline bool Nuvem::has_size() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Nuvem::set_has_size() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Nuvem::clear_has_size() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Nuvem::clear_size() {
  size_ = 0;
  clear_has_size();
}
inline ::google::protobuf::int32 Nuvem::size() const {
  // @@protoc_insertion_point(field_get:NuvemMsgProto.Nuvem.size)
  return size_;
}
inline void Nuvem::set_size(::google::protobuf::int32 value) {
  set_has_size();
  size_ = value;
  // @@protoc_insertion_point(field_set:NuvemMsgProto.Nuvem.size)
}

// repeated .NuvemMsgProto.Nuvem.Ponto pontos = 3;
inline int Nuvem::pontos_size() const {
  return pontos_.size();
}
inline void Nuvem::clear_pontos() {
  pontos_.Clear();
}
inline const ::NuvemMsgProto::Nuvem_Ponto& Nuvem::pontos(int index) const {
  // @@protoc_insertion_point(field_get:NuvemMsgProto.Nuvem.pontos)
  return pontos_.Get(index);
}
inline ::NuvemMsgProto::Nuvem_Ponto* Nuvem::mutable_pontos(int index) {
  // @@protoc_insertion_point(field_mutable:NuvemMsgProto.Nuvem.pontos)
  return pontos_.Mutable(index);
}
inline ::NuvemMsgProto::Nuvem_Ponto* Nuvem::add_pontos() {
  // @@protoc_insertion_point(field_add:NuvemMsgProto.Nuvem.pontos)
  return pontos_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::NuvemMsgProto::Nuvem_Ponto >*
Nuvem::mutable_pontos() {
  // @@protoc_insertion_point(field_mutable_list:NuvemMsgProto.Nuvem.pontos)
  return &pontos_;
}
inline const ::google::protobuf::RepeatedPtrField< ::NuvemMsgProto::Nuvem_Ponto >&
Nuvem::pontos() const {
  // @@protoc_insertion_point(field_list:NuvemMsgProto.Nuvem.pontos)
  return pontos_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace NuvemMsgProto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_nuvem_2eproto__INCLUDED
