// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nuvem.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "nuvem.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace NuvemMsgProto {
class Nuvem_PontoDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Nuvem_Ponto> {
} _Nuvem_Ponto_default_instance_;
class NuvemDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Nuvem> {
} _Nuvem_default_instance_;

namespace protobuf_nuvem_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Nuvem_Ponto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Nuvem_Ponto, x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Nuvem_Ponto, y_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Nuvem_Ponto, z_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Nuvem_Ponto, r_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Nuvem_Ponto, g_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Nuvem_Ponto, b_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Nuvem, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Nuvem, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Nuvem, size_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Nuvem, pontos_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(Nuvem_Ponto)},
  { 10, -1, sizeof(Nuvem)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_Nuvem_Ponto_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_Nuvem_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "nuvem.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace

void TableStruct::Shutdown() {
  _Nuvem_Ponto_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _Nuvem_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _Nuvem_Ponto_default_instance_.DefaultConstruct();
  _Nuvem_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\013nuvem.proto\022\rNuvemMsgProto\"\232\001\n\005Nuvem\022\014"
      "\n\004name\030\001 \001(\t\022\014\n\004size\030\002 \001(\005\022*\n\006pontos\030\003 \003"
      "(\0132\032.NuvemMsgProto.Nuvem.Ponto\032I\n\005Ponto\022"
      "\t\n\001x\030\001 \001(\001\022\t\n\001y\030\002 \001(\001\022\t\n\001z\030\003 \001(\001\022\t\n\001r\030\004 "
      "\001(\005\022\t\n\001g\030\005 \001(\005\022\t\n\001b\030\006 \001(\005b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 193);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "nuvem.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_nuvem_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Nuvem_Ponto::kXFieldNumber;
const int Nuvem_Ponto::kYFieldNumber;
const int Nuvem_Ponto::kZFieldNumber;
const int Nuvem_Ponto::kRFieldNumber;
const int Nuvem_Ponto::kGFieldNumber;
const int Nuvem_Ponto::kBFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Nuvem_Ponto::Nuvem_Ponto()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_nuvem_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:NuvemMsgProto.Nuvem.Ponto)
}
Nuvem_Ponto::Nuvem_Ponto(const Nuvem_Ponto& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&x_, &from.x_,
    reinterpret_cast<char*>(&b_) -
    reinterpret_cast<char*>(&x_) + sizeof(b_));
  // @@protoc_insertion_point(copy_constructor:NuvemMsgProto.Nuvem.Ponto)
}

void Nuvem_Ponto::SharedCtor() {
  ::memset(&x_, 0, reinterpret_cast<char*>(&b_) -
    reinterpret_cast<char*>(&x_) + sizeof(b_));
  _cached_size_ = 0;
}

Nuvem_Ponto::~Nuvem_Ponto() {
  // @@protoc_insertion_point(destructor:NuvemMsgProto.Nuvem.Ponto)
  SharedDtor();
}

void Nuvem_Ponto::SharedDtor() {
}

void Nuvem_Ponto::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Nuvem_Ponto::descriptor() {
  protobuf_nuvem_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_nuvem_2eproto::file_level_metadata[0].descriptor;
}

const Nuvem_Ponto& Nuvem_Ponto::default_instance() {
  protobuf_nuvem_2eproto::InitDefaults();
  return *internal_default_instance();
}

Nuvem_Ponto* Nuvem_Ponto::New(::google::protobuf::Arena* arena) const {
  Nuvem_Ponto* n = new Nuvem_Ponto;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Nuvem_Ponto::Clear() {
// @@protoc_insertion_point(message_clear_start:NuvemMsgProto.Nuvem.Ponto)
  ::memset(&x_, 0, reinterpret_cast<char*>(&b_) -
    reinterpret_cast<char*>(&x_) + sizeof(b_));
}

bool Nuvem_Ponto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:NuvemMsgProto.Nuvem.Ponto)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // double x = 1;
      case 1: {
        if (tag == 9u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double y = 2;
      case 2: {
        if (tag == 17u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double z = 3;
      case 3: {
        if (tag == 25u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &z_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 r = 4;
      case 4: {
        if (tag == 32u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &r_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 g = 5;
      case 5: {
        if (tag == 40u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &g_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 b = 6;
      case 6: {
        if (tag == 48u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &b_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:NuvemMsgProto.Nuvem.Ponto)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:NuvemMsgProto.Nuvem.Ponto)
  return false;
#undef DO_
}

void Nuvem_Ponto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:NuvemMsgProto.Nuvem.Ponto)
  // double x = 1;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->x(), output);
  }

  // double y = 2;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->y(), output);
  }

  // double z = 3;
  if (this->z() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->z(), output);
  }

  // int32 r = 4;
  if (this->r() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->r(), output);
  }

  // int32 g = 5;
  if (this->g() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->g(), output);
  }

  // int32 b = 6;
  if (this->b() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->b(), output);
  }

  // @@protoc_insertion_point(serialize_end:NuvemMsgProto.Nuvem.Ponto)
}

::google::protobuf::uint8* Nuvem_Ponto::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:NuvemMsgProto.Nuvem.Ponto)
  // double x = 1;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->x(), target);
  }

  // double y = 2;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->y(), target);
  }

  // double z = 3;
  if (this->z() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->z(), target);
  }

  // int32 r = 4;
  if (this->r() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->r(), target);
  }

  // int32 g = 5;
  if (this->g() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->g(), target);
  }

  // int32 b = 6;
  if (this->b() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->b(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:NuvemMsgProto.Nuvem.Ponto)
  return target;
}

size_t Nuvem_Ponto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NuvemMsgProto.Nuvem.Ponto)
  size_t total_size = 0;

  // double x = 1;
  if (this->x() != 0) {
    total_size += 1 + 8;
  }

  // double y = 2;
  if (this->y() != 0) {
    total_size += 1 + 8;
  }

  // double z = 3;
  if (this->z() != 0) {
    total_size += 1 + 8;
  }

  // int32 r = 4;
  if (this->r() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->r());
  }

  // int32 g = 5;
  if (this->g() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->g());
  }

  // int32 b = 6;
  if (this->b() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->b());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Nuvem_Ponto::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:NuvemMsgProto.Nuvem.Ponto)
  GOOGLE_DCHECK_NE(&from, this);
  const Nuvem_Ponto* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Nuvem_Ponto>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:NuvemMsgProto.Nuvem.Ponto)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:NuvemMsgProto.Nuvem.Ponto)
    MergeFrom(*source);
  }
}

void Nuvem_Ponto::MergeFrom(const Nuvem_Ponto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:NuvemMsgProto.Nuvem.Ponto)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
  if (from.z() != 0) {
    set_z(from.z());
  }
  if (from.r() != 0) {
    set_r(from.r());
  }
  if (from.g() != 0) {
    set_g(from.g());
  }
  if (from.b() != 0) {
    set_b(from.b());
  }
}

void Nuvem_Ponto::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:NuvemMsgProto.Nuvem.Ponto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Nuvem_Ponto::CopyFrom(const Nuvem_Ponto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NuvemMsgProto.Nuvem.Ponto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Nuvem_Ponto::IsInitialized() const {
  return true;
}

void Nuvem_Ponto::Swap(Nuvem_Ponto* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Nuvem_Ponto::InternalSwap(Nuvem_Ponto* other) {
  std::swap(x_, other->x_);
  std::swap(y_, other->y_);
  std::swap(z_, other->z_);
  std::swap(r_, other->r_);
  std::swap(g_, other->g_);
  std::swap(b_, other->b_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Nuvem_Ponto::GetMetadata() const {
  protobuf_nuvem_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_nuvem_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Nuvem_Ponto

// double x = 1;
void Nuvem_Ponto::clear_x() {
  x_ = 0;
}
double Nuvem_Ponto::x() const {
  // @@protoc_insertion_point(field_get:NuvemMsgProto.Nuvem.Ponto.x)
  return x_;
}
void Nuvem_Ponto::set_x(double value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:NuvemMsgProto.Nuvem.Ponto.x)
}

// double y = 2;
void Nuvem_Ponto::clear_y() {
  y_ = 0;
}
double Nuvem_Ponto::y() const {
  // @@protoc_insertion_point(field_get:NuvemMsgProto.Nuvem.Ponto.y)
  return y_;
}
void Nuvem_Ponto::set_y(double value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:NuvemMsgProto.Nuvem.Ponto.y)
}

// double z = 3;
void Nuvem_Ponto::clear_z() {
  z_ = 0;
}
double Nuvem_Ponto::z() const {
  // @@protoc_insertion_point(field_get:NuvemMsgProto.Nuvem.Ponto.z)
  return z_;
}
void Nuvem_Ponto::set_z(double value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:NuvemMsgProto.Nuvem.Ponto.z)
}

// int32 r = 4;
void Nuvem_Ponto::clear_r() {
  r_ = 0;
}
::google::protobuf::int32 Nuvem_Ponto::r() const {
  // @@protoc_insertion_point(field_get:NuvemMsgProto.Nuvem.Ponto.r)
  return r_;
}
void Nuvem_Ponto::set_r(::google::protobuf::int32 value) {
  
  r_ = value;
  // @@protoc_insertion_point(field_set:NuvemMsgProto.Nuvem.Ponto.r)
}

// int32 g = 5;
void Nuvem_Ponto::clear_g() {
  g_ = 0;
}
::google::protobuf::int32 Nuvem_Ponto::g() const {
  // @@protoc_insertion_point(field_get:NuvemMsgProto.Nuvem.Ponto.g)
  return g_;
}
void Nuvem_Ponto::set_g(::google::protobuf::int32 value) {
  
  g_ = value;
  // @@protoc_insertion_point(field_set:NuvemMsgProto.Nuvem.Ponto.g)
}

// int32 b = 6;
void Nuvem_Ponto::clear_b() {
  b_ = 0;
}
::google::protobuf::int32 Nuvem_Ponto::b() const {
  // @@protoc_insertion_point(field_get:NuvemMsgProto.Nuvem.Ponto.b)
  return b_;
}
void Nuvem_Ponto::set_b(::google::protobuf::int32 value) {
  
  b_ = value;
  // @@protoc_insertion_point(field_set:NuvemMsgProto.Nuvem.Ponto.b)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Nuvem::kNameFieldNumber;
const int Nuvem::kSizeFieldNumber;
const int Nuvem::kPontosFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Nuvem::Nuvem()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_nuvem_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:NuvemMsgProto.Nuvem)
}
Nuvem::Nuvem(const Nuvem& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      pontos_(from.pontos_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  size_ = from.size_;
  // @@protoc_insertion_point(copy_constructor:NuvemMsgProto.Nuvem)
}

void Nuvem::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  size_ = 0;
  _cached_size_ = 0;
}

Nuvem::~Nuvem() {
  // @@protoc_insertion_point(destructor:NuvemMsgProto.Nuvem)
  SharedDtor();
}

void Nuvem::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Nuvem::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Nuvem::descriptor() {
  protobuf_nuvem_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_nuvem_2eproto::file_level_metadata[1].descriptor;
}

const Nuvem& Nuvem::default_instance() {
  protobuf_nuvem_2eproto::InitDefaults();
  return *internal_default_instance();
}

Nuvem* Nuvem::New(::google::protobuf::Arena* arena) const {
  Nuvem* n = new Nuvem;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Nuvem::Clear() {
// @@protoc_insertion_point(message_clear_start:NuvemMsgProto.Nuvem)
  pontos_.Clear();
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  size_ = 0;
}

bool Nuvem::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:NuvemMsgProto.Nuvem)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string name = 1;
      case 1: {
        if (tag == 10u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "NuvemMsgProto.Nuvem.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 size = 2;
      case 2: {
        if (tag == 16u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &size_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .NuvemMsgProto.Nuvem.Ponto pontos = 3;
      case 3: {
        if (tag == 26u) {
          DO_(input->IncrementRecursionDepth());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_pontos()));
        } else {
          goto handle_unusual;
        }
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:NuvemMsgProto.Nuvem)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:NuvemMsgProto.Nuvem)
  return false;
#undef DO_
}

void Nuvem::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:NuvemMsgProto.Nuvem)
  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "NuvemMsgProto.Nuvem.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // int32 size = 2;
  if (this->size() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->size(), output);
  }

  // repeated .NuvemMsgProto.Nuvem.Ponto pontos = 3;
  for (unsigned int i = 0, n = this->pontos_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->pontos(i), output);
  }

  // @@protoc_insertion_point(serialize_end:NuvemMsgProto.Nuvem)
}

::google::protobuf::uint8* Nuvem::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:NuvemMsgProto.Nuvem)
  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "NuvemMsgProto.Nuvem.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // int32 size = 2;
  if (this->size() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->size(), target);
  }

  // repeated .NuvemMsgProto.Nuvem.Ponto pontos = 3;
  for (unsigned int i = 0, n = this->pontos_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, this->pontos(i), false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:NuvemMsgProto.Nuvem)
  return target;
}

size_t Nuvem::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NuvemMsgProto.Nuvem)
  size_t total_size = 0;

  // repeated .NuvemMsgProto.Nuvem.Ponto pontos = 3;
  {
    unsigned int count = this->pontos_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->pontos(i));
    }
  }

  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // int32 size = 2;
  if (this->size() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->size());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Nuvem::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:NuvemMsgProto.Nuvem)
  GOOGLE_DCHECK_NE(&from, this);
  const Nuvem* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Nuvem>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:NuvemMsgProto.Nuvem)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:NuvemMsgProto.Nuvem)
    MergeFrom(*source);
  }
}

void Nuvem::MergeFrom(const Nuvem& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:NuvemMsgProto.Nuvem)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  pontos_.MergeFrom(from.pontos_);
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.size() != 0) {
    set_size(from.size());
  }
}

void Nuvem::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:NuvemMsgProto.Nuvem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Nuvem::CopyFrom(const Nuvem& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NuvemMsgProto.Nuvem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Nuvem::IsInitialized() const {
  return true;
}

void Nuvem::Swap(Nuvem* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Nuvem::InternalSwap(Nuvem* other) {
  pontos_.UnsafeArenaSwap(&other->pontos_);
  name_.Swap(&other->name_);
  std::swap(size_, other->size_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Nuvem::GetMetadata() const {
  protobuf_nuvem_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_nuvem_2eproto::file_level_metadata[1];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Nuvem

// string name = 1;
void Nuvem::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& Nuvem::name() const {
  // @@protoc_insertion_point(field_get:NuvemMsgProto.Nuvem.name)
  return name_.GetNoArena();
}
void Nuvem::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:NuvemMsgProto.Nuvem.name)
}
#if LANG_CXX11
void Nuvem::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:NuvemMsgProto.Nuvem.name)
}
#endif
void Nuvem::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:NuvemMsgProto.Nuvem.name)
}
void Nuvem::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:NuvemMsgProto.Nuvem.name)
}
::std::string* Nuvem::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:NuvemMsgProto.Nuvem.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Nuvem::release_name() {
  // @@protoc_insertion_point(field_release:NuvemMsgProto.Nuvem.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Nuvem::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:NuvemMsgProto.Nuvem.name)
}

// int32 size = 2;
void Nuvem::clear_size() {
  size_ = 0;
}
::google::protobuf::int32 Nuvem::size() const {
  // @@protoc_insertion_point(field_get:NuvemMsgProto.Nuvem.size)
  return size_;
}
void Nuvem::set_size(::google::protobuf::int32 value) {
  
  size_ = value;
  // @@protoc_insertion_point(field_set:NuvemMsgProto.Nuvem.size)
}

// repeated .NuvemMsgProto.Nuvem.Ponto pontos = 3;
int Nuvem::pontos_size() const {
  return pontos_.size();
}
void Nuvem::clear_pontos() {
  pontos_.Clear();
}
const ::NuvemMsgProto::Nuvem_Ponto& Nuvem::pontos(int index) const {
  // @@protoc_insertion_point(field_get:NuvemMsgProto.Nuvem.pontos)
  return pontos_.Get(index);
}
::NuvemMsgProto::Nuvem_Ponto* Nuvem::mutable_pontos(int index) {
  // @@protoc_insertion_point(field_mutable:NuvemMsgProto.Nuvem.pontos)
  return pontos_.Mutable(index);
}
::NuvemMsgProto::Nuvem_Ponto* Nuvem::add_pontos() {
  // @@protoc_insertion_point(field_add:NuvemMsgProto.Nuvem.pontos)
  return pontos_.Add();
}
::google::protobuf::RepeatedPtrField< ::NuvemMsgProto::Nuvem_Ponto >*
Nuvem::mutable_pontos() {
  // @@protoc_insertion_point(field_mutable_list:NuvemMsgProto.Nuvem.pontos)
  return &pontos_;
}
const ::google::protobuf::RepeatedPtrField< ::NuvemMsgProto::Nuvem_Ponto >&
Nuvem::pontos() const {
  // @@protoc_insertion_point(field_list:NuvemMsgProto.Nuvem.pontos)
  return pontos_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace NuvemMsgProto

// @@protoc_insertion_point(global_scope)
