// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nuvem.proto

#ifndef PROTOBUF_nuvem_2eproto__INCLUDED
#define PROTOBUF_nuvem_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace NuvemMsgProto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_nuvem_2eproto();
void protobuf_AssignDesc_nuvem_2eproto();
void protobuf_ShutdownFile_nuvem_2eproto();

class Nuvem;
class Nuvem_Ponto;

// ===================================================================

class Nuvem_Ponto : public ::google::protobuf::Message {
 public:
  Nuvem_Ponto();
  virtual ~Nuvem_Ponto();

  Nuvem_Ponto(const Nuvem_Ponto& from);

  inline Nuvem_Ponto& operator=(const Nuvem_Ponto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Nuvem_Ponto& default_instance();

  void Swap(Nuvem_Ponto* other);

  // implements Message ----------------------------------------------

  Nuvem_Ponto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Nuvem_Ponto& from);
  void MergeFrom(const Nuvem_Ponto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double x = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline double x() const;
  inline void set_x(double value);

  // required double y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline double y() const;
  inline void set_y(double value);

  // required double z = 3;
  inline bool has_z() const;
  inline void clear_z();
  static const int kZFieldNumber = 3;
  inline double z() const;
  inline void set_z(double value);

  // required int32 r = 4;
  inline bool has_r() const;
  inline void clear_r();
  static const int kRFieldNumber = 4;
  inline ::google::protobuf::int32 r() const;
  inline void set_r(::google::protobuf::int32 value);

  // required int32 g = 5;
  inline bool has_g() const;
  inline void clear_g();
  static const int kGFieldNumber = 5;
  inline ::google::protobuf::int32 g() const;
  inline void set_g(::google::protobuf::int32 value);

  // required int32 b = 6;
  inline bool has_b() const;
  inline void clear_b();
  static const int kBFieldNumber = 6;
  inline ::google::protobuf::int32 b() const;
  inline void set_b(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:NuvemMsgProto.Nuvem.Ponto)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_z();
  inline void clear_has_z();
  inline void set_has_r();
  inline void clear_has_r();
  inline void set_has_g();
  inline void clear_has_g();
  inline void set_has_b();
  inline void clear_has_b();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double x_;
  double y_;
  double z_;
  ::google::protobuf::int32 r_;
  ::google::protobuf::int32 g_;
  ::google::protobuf::int32 b_;
  friend void  protobuf_AddDesc_nuvem_2eproto();
  friend void protobuf_AssignDesc_nuvem_2eproto();
  friend void protobuf_ShutdownFile_nuvem_2eproto();

  void InitAsDefaultInstance();
  static Nuvem_Ponto* default_instance_;
};
// -------------------------------------------------------------------

class Nuvem : public ::google::protobuf::Message {
 public:
  Nuvem();
  virtual ~Nuvem();

  Nuvem(const Nuvem& from);

  inline Nuvem& operator=(const Nuvem& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Nuvem& default_instance();

  void Swap(Nuvem* other);

  // implements Message ----------------------------------------------

  Nuvem* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Nuvem& from);
  void MergeFrom(const Nuvem& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Nuvem_Ponto Ponto;

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required int32 size = 2;
  inline bool has_size() const;
  inline void clear_size();
  static const int kSizeFieldNumber = 2;
  inline ::google::protobuf::int32 size() const;
  inline void set_size(::google::protobuf::int32 value);

  // repeated .NuvemMsgProto.Nuvem.Ponto pontos = 3;
  inline int pontos_size() const;
  inline void clear_pontos();
  static const int kPontosFieldNumber = 3;
  inline const ::NuvemMsgProto::Nuvem_Ponto& pontos(int index) const;
  inline ::NuvemMsgProto::Nuvem_Ponto* mutable_pontos(int index);
  inline ::NuvemMsgProto::Nuvem_Ponto* add_pontos();
  inline const ::google::protobuf::RepeatedPtrField< ::NuvemMsgProto::Nuvem_Ponto >&
      pontos() const;
  inline ::google::protobuf::RepeatedPtrField< ::NuvemMsgProto::Nuvem_Ponto >*
      mutable_pontos();

  // @@protoc_insertion_point(class_scope:NuvemMsgProto.Nuvem)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_size();
  inline void clear_has_size();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  ::google::protobuf::RepeatedPtrField< ::NuvemMsgProto::Nuvem_Ponto > pontos_;
  ::google::protobuf::int32 size_;
  friend void  protobuf_AddDesc_nuvem_2eproto();
  friend void protobuf_AssignDesc_nuvem_2eproto();
  friend void protobuf_ShutdownFile_nuvem_2eproto();

  void InitAsDefaultInstance();
  static Nuvem* default_instance_;
};
// ===================================================================


// ===================================================================

// Nuvem_Ponto

// required double x = 1;
inline bool Nuvem_Ponto::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Nuvem_Ponto::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Nuvem_Ponto::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Nuvem_Ponto::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline double Nuvem_Ponto::x() const {
  // @@protoc_insertion_point(field_get:NuvemMsgProto.Nuvem.Ponto.x)
  return x_;
}
inline void Nuvem_Ponto::set_x(double value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:NuvemMsgProto.Nuvem.Ponto.x)
}

// required double y = 2;
inline bool Nuvem_Ponto::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Nuvem_Ponto::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Nuvem_Ponto::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Nuvem_Ponto::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline double Nuvem_Ponto::y() const {
  // @@protoc_insertion_point(field_get:NuvemMsgProto.Nuvem.Ponto.y)
  return y_;
}
inline void Nuvem_Ponto::set_y(double value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:NuvemMsgProto.Nuvem.Ponto.y)
}

// required double z = 3;
inline bool Nuvem_Ponto::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Nuvem_Ponto::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Nuvem_Ponto::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Nuvem_Ponto::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline double Nuvem_Ponto::z() const {
  // @@protoc_insertion_point(field_get:NuvemMsgProto.Nuvem.Ponto.z)
  return z_;
}
inline void Nuvem_Ponto::set_z(double value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:NuvemMsgProto.Nuvem.Ponto.z)
}

// required int32 r = 4;
inline bool Nuvem_Ponto::has_r() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Nuvem_Ponto::set_has_r() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Nuvem_Ponto::clear_has_r() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Nuvem_Ponto::clear_r() {
  r_ = 0;
  clear_has_r();
}
inline ::google::protobuf::int32 Nuvem_Ponto::r() const {
  // @@protoc_insertion_point(field_get:NuvemMsgProto.Nuvem.Ponto.r)
  return r_;
}
inline void Nuvem_Ponto::set_r(::google::protobuf::int32 value) {
  set_has_r();
  r_ = value;
  // @@protoc_insertion_point(field_set:NuvemMsgProto.Nuvem.Ponto.r)
}

// required int32 g = 5;
inline bool Nuvem_Ponto::has_g() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Nuvem_Ponto::set_has_g() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Nuvem_Ponto::clear_has_g() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Nuvem_Ponto::clear_g() {
  g_ = 0;
  clear_has_g();
}
inline ::google::protobuf::int32 Nuvem_Ponto::g() const {
  // @@protoc_insertion_point(field_get:NuvemMsgProto.Nuvem.Ponto.g)
  return g_;
}
inline void Nuvem_Ponto::set_g(::google::protobuf::int32 value) {
  set_has_g();
  g_ = value;
  // @@protoc_insertion_point(field_set:NuvemMsgProto.Nuvem.Ponto.g)
}

// required int32 b = 6;
inline bool Nuvem_Ponto::has_b() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Nuvem_Ponto::set_has_b() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Nuvem_Ponto::clear_has_b() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Nuvem_Ponto::clear_b() {
  b_ = 0;
  clear_has_b();
}
inline ::google::protobuf::int32 Nuvem_Ponto::b() const {
  // @@protoc_insertion_point(field_get:NuvemMsgProto.Nuvem.Ponto.b)
  return b_;
}
inline void Nuvem_Ponto::set_b(::google::protobuf::int32 value) {
  set_has_b();
  b_ = value;
  // @@protoc_insertion_point(field_set:NuvemMsgProto.Nuvem.Ponto.b)
}

// -------------------------------------------------------------------

// Nuvem

// required string name = 1;
inline bool Nuvem::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Nuvem::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Nuvem::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Nuvem::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Nuvem::name() const {
  // @@protoc_insertion_point(field_get:NuvemMsgProto.Nuvem.name)
  return *name_;
}
inline void Nuvem::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:NuvemMsgProto.Nuvem.name)
}
inline void Nuvem::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:NuvemMsgProto.Nuvem.name)
}
inline void Nuvem::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:NuvemMsgProto.Nuvem.name)
}
inline ::std::string* Nuvem::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:NuvemMsgProto.Nuvem.name)
  return name_;
}
inline ::std::string* Nuvem::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Nuvem::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:NuvemMsgProto.Nuvem.name)
}

// required int32 size = 2;
inline bool Nuvem::has_size() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Nuvem::set_has_size() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Nuvem::clear_has_size() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Nuvem::clear_size() {
  size_ = 0;
  clear_has_size();
}
inline ::google::protobuf::int32 Nuvem::size() const {
  // @@protoc_insertion_point(field_get:NuvemMsgProto.Nuvem.size)
  return size_;
}
inline void Nuvem::set_size(::google::protobuf::int32 value) {
  set_has_size();
  size_ = value;
  // @@protoc_insertion_point(field_set:NuvemMsgProto.Nuvem.size)
}

// repeated .NuvemMsgProto.Nuvem.Ponto pontos = 3;
inline int Nuvem::pontos_size() const {
  return pontos_.size();
}
inline void Nuvem::clear_pontos() {
  pontos_.Clear();
}
inline const ::NuvemMsgProto::Nuvem_Ponto& Nuvem::pontos(int index) const {
  // @@protoc_insertion_point(field_get:NuvemMsgProto.Nuvem.pontos)
  return pontos_.Get(index);
}
inline ::NuvemMsgProto::Nuvem_Ponto* Nuvem::mutable_pontos(int index) {
  // @@protoc_insertion_point(field_mutable:NuvemMsgProto.Nuvem.pontos)
  return pontos_.Mutable(index);
}
inline ::NuvemMsgProto::Nuvem_Ponto* Nuvem::add_pontos() {
  // @@protoc_insertion_point(field_add:NuvemMsgProto.Nuvem.pontos)
  return pontos_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::NuvemMsgProto::Nuvem_Ponto >&
Nuvem::pontos() const {
  // @@protoc_insertion_point(field_list:NuvemMsgProto.Nuvem.pontos)
  return pontos_;
}
inline ::google::protobuf::RepeatedPtrField< ::NuvemMsgProto::Nuvem_Ponto >*
Nuvem::mutable_pontos() {
  // @@protoc_insertion_point(field_mutable_list:NuvemMsgProto.Nuvem.pontos)
  return &pontos_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace NuvemMsgProto

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_nuvem_2eproto__INCLUDED
