// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nvm.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "nvm.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace NVMMsgProto {

namespace {

const ::google::protobuf::Descriptor* NVM_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  NVM_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_nvm_2eproto() {
  protobuf_AddDesc_nvm_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "nvm.proto");
  GOOGLE_CHECK(file != NULL);
  NVM_descriptor_ = file->message_type(0);
  static const int NVM_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NVM, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NVM, nlinhas_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NVM, linhas_),
  };
  NVM_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      NVM_descriptor_,
      NVM::default_instance_,
      NVM_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NVM, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NVM, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(NVM));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_nvm_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    NVM_descriptor_, &NVM::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_nvm_2eproto() {
  delete NVM::default_instance_;
  delete NVM_reflection_;
}

void protobuf_AddDesc_nvm_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\tnvm.proto\022\013NVMMsgProto\"4\n\003NVM\022\014\n\004name\030"
    "\001 \002(\t\022\017\n\007nlinhas\030\002 \002(\005\022\016\n\006linhas\030\003 \003(\t", 78);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "nvm.proto", &protobuf_RegisterTypes);
  NVM::default_instance_ = new NVM();
  NVM::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_nvm_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_nvm_2eproto {
  StaticDescriptorInitializer_nvm_2eproto() {
    protobuf_AddDesc_nvm_2eproto();
  }
} static_descriptor_initializer_nvm_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int NVM::kNameFieldNumber;
const int NVM::kNlinhasFieldNumber;
const int NVM::kLinhasFieldNumber;
#endif  // !_MSC_VER

NVM::NVM()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:NVMMsgProto.NVM)
}

void NVM::InitAsDefaultInstance() {
}

NVM::NVM(const NVM& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:NVMMsgProto.NVM)
}

void NVM::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  nlinhas_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

NVM::~NVM() {
  // @@protoc_insertion_point(destructor:NVMMsgProto.NVM)
  SharedDtor();
}

void NVM::SharedDtor() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (this != default_instance_) {
  }
}

void NVM::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* NVM::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return NVM_descriptor_;
}

const NVM& NVM::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_nvm_2eproto();
  return *default_instance_;
}

NVM* NVM::default_instance_ = NULL;

NVM* NVM::New() const {
  return new NVM;
}

void NVM::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        name_->clear();
      }
    }
    nlinhas_ = 0;
  }
  linhas_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool NVM::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:NVMMsgProto.NVM)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_nlinhas;
        break;
      }

      // required int32 nlinhas = 2;
      case 2: {
        if (tag == 16) {
         parse_nlinhas:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &nlinhas_)));
          set_has_nlinhas();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_linhas;
        break;
      }

      // repeated string linhas = 3;
      case 3: {
        if (tag == 26) {
         parse_linhas:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_linhas()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->linhas(this->linhas_size() - 1).data(),
            this->linhas(this->linhas_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "linhas");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_linhas;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:NVMMsgProto.NVM)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:NVMMsgProto.NVM)
  return false;
#undef DO_
}

void NVM::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:NVMMsgProto.NVM)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // required int32 nlinhas = 2;
  if (has_nlinhas()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->nlinhas(), output);
  }

  // repeated string linhas = 3;
  for (int i = 0; i < this->linhas_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
    this->linhas(i).data(), this->linhas(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE,
    "linhas");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->linhas(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:NVMMsgProto.NVM)
}

::google::protobuf::uint8* NVM::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:NVMMsgProto.NVM)
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // required int32 nlinhas = 2;
  if (has_nlinhas()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->nlinhas(), target);
  }

  // repeated string linhas = 3;
  for (int i = 0; i < this->linhas_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->linhas(i).data(), this->linhas(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "linhas");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(3, this->linhas(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NVMMsgProto.NVM)
  return target;
}

int NVM::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // required int32 nlinhas = 2;
    if (has_nlinhas()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->nlinhas());
    }

  }
  // repeated string linhas = 3;
  total_size += 1 * this->linhas_size();
  for (int i = 0; i < this->linhas_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->linhas(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void NVM::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const NVM* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const NVM*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void NVM::MergeFrom(const NVM& from) {
  GOOGLE_CHECK_NE(&from, this);
  linhas_.MergeFrom(from.linhas_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_nlinhas()) {
      set_nlinhas(from.nlinhas());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void NVM::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NVM::CopyFrom(const NVM& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NVM::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void NVM::Swap(NVM* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(nlinhas_, other->nlinhas_);
    linhas_.Swap(&other->linhas_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata NVM::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = NVM_descriptor_;
  metadata.reflection = NVM_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace NVMMsgProto

// @@protoc_insertion_point(global_scope)
